name: Test strategii

on:
  workflow_dispatch:  # Allows manual trigger
 # schedule: ONLY MANUAL
 #   - cron: "0 0 * * *"  # Runs daily at midn UTC

jobs: 
  process_stooq_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python deps
        run: |
          pip install  pandas numpy requests  google-api-python-client

      
      #- name: Create Google Credentials File
      #  run: |
      #    echo '${{ secrets.GOOGLE_CREDENTIALS }}' > /tmp/credentials.json
          
     
      #- name: Validate JSON Format
      #  run: |
      #    python -c "import json; json.load(open('/tmp/credentials.json'))" && echo "JSON is valid."
          
   

      #- name: Set range of indexes and run Python script
      #  env:
      #    MIN_INDEX: 1006
      #    MAX_INDEX: 1008 
      #    CSV_BASE_URL: ${{ secrets.CSV_BASE_URL }}
      #    FOLDER_NAME: ${{ secrets.FOLDER_NAME }} 
          
        run: |
          python Strat_test_work.py
      
      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: download-logs
          path: download.log

